### ISSUE TITLE
Play video by URL?

### ISSUE THREAD

**Issue by Xarin** [mps-youtube/yewtube#100]
It should be fairly simple, would it be possible for you to add a feature to play/listen to a video by URL.

Edit: Thx for the help!

**Comment by Aneeqasif** [comment]
mpsyt playurl ZSzeFFsKEt4 -a
usage: mpsyt [--help] [--version] [--debug] [--logging] [--no-autosize] [--no-preload]
             [--no-textart]
             [commands ...]
mpsyt: error: unrecognized arguments: -a
