### ISSUE TITLE
MPSYT stops playing videos/songs halfway (ish) and exits to the search menu

### ISSUE THREAD

**Issue by Jachdich** [mps-youtube/yewtube#1004]
## Issue

Pretty self explanatory. At an unknown point whilst playing it just crashes back to this screen: http://i.imgur.com/9LAIfAh.png

Happens with multiple test songs I've tried.

## Environment

Output of `mpsyt --version`
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.08.13
Python version     : 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.15.0-58-generic-x86_64-with-LinuxMint-18.3-sylvia
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/sage/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_GB.UTF-8
env:LANGUAGE       : en_GB:en

**Comment by ablizno** [comment]
its a unicode thing, look up up. Someone in here solved it but I'm too lazy to find it. UTF-8 has to be placed somewhere

**Comment by nchristensen** [comment]
I have this problem as well. Every song I play terminates early. I searched for issues related to UTF-8 but saw nothing obviously related to this problem.

### Environment
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.11.05
Python version     : 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/user/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : fr_FR.UTF-8
env:LANGUAGE       : fr_FR

**Comment by nchristensen** [comment]
Switching from mplayer to mpv appears to have fixed my problem.
