### ISSUE TITLE
Build 32-bit exe please

### ISSUE THREAD

**Issue by ahmedtds** [mps-youtube/yewtube#1035]
Can you build a 32-bit exe please?

64bit OS can run 32bit apps but 32bit OS can't run 64bit apps. It doesn't make sense to build only 64bit instead of 32bit if you are gonna build for only one platform because 32bit apps can be run by both but 64bit apps can only be run by one of them.

Thanks!

**Comment by RMuskovets** [comment]
Python 3 is available for 32-bit systems. All the dependencies work with 32-bit. Most people have 64-bit, and this is the reason Chrome, Sublime Text, many games release apps only for 64-bit systems.
However, you can download Python 3, install all the dependencies and run mpsyt using "python mpsyt". I don't see a problem - do you?

**Comment by ahmedtds** [comment]
I just requested 32-bit standalone exe file. They already release standalone exe file but it's 64-bit. I just said it's more sensible to release it as 32-bit instead of 64-bit only.

None of things you said is relevant. This is not a 250GB AAA game, you don't need 64-bit for a console app, Chrome or Sublime Text doesn't release only for 64-bit systems no, you're wrong on that. Both has 32bit support. Get your facts straight.

Have no idea what's the purpose of your message, no need to object something that doesn't interest you.

**Comment by RMuskovets** [comment]
Okay, I was looking on Linux files. Sorry. I meant, as long as you're able to get all the sources and dependencies, you can easily build mps-youtube yourself. ;)

**Comment by ahmedtds** [comment]
Oh ok all good sorry for misunderstanding, cheers.

**Comment by ahmedtds** [comment]
Last standalone exe release is from 2018: https://github.com/mps-youtube/mps-youtube/releases

Project is still active, getting code changes, why not release a standalone exe once in a while? 2,5 years is a long time, no?
