### ISSUE TITLE
List of dependencies in Readme?

### ISSUE THREAD

**Issue by vol-2** [mps-youtube/yewtube#1040]
## Issue / Suggestion

Is there some list of programs or packages that I must install before mps youtube?

## Your Environment

Running on a raspberry pi 4 with raspbian buster.

**Comment by mandaputtra** [comment]
youtube-dl

**Comment by vol-2** [comment]
> youtube-dl

this is the one and only dependency for mps-youtube?

**Comment by iamtalhaasghar** [comment]
See `requirements.txt` file.

**Comment by vol-2** [comment]
Thanks!

Can I assume that lines 2 and 6 are only necessary for Windows environment?

Also, youtube-search-python is on 1.6.6, but the reqs file say 1.6.5. Does it matter which one I use?

As a side note, youtube-search-python says that it is no longer maintained because the code is bad and it's too buggy to fix. https://github.com/alexmercerind/youtube-search-python/issues/189

Might be worth looking into.

**Comment by iamtalhaasghar** [comment]
You dont have worry about minor details of dependencies.
Just create a new `venv` and do `pip install -r requirements.txt`.

Yeah i know `youtube-search-python` is not being maintained.
