### ISSUE TITLE
Ignore URL query parameters

### ISSUE THREAD

**Issue by Semior001** [mps-youtube/yewtube#1051]
Example: command `mpsyt dlurl https://www.youtube.com/watch?v=7LGTEI1RMoQ&t=4` closes the application without showing a list of downloadable items.

Is it necessary to consider the url with any other query parameter, except 'v'? Is it possible to ignore them?

**Comment by iamtalhaasghar** [comment]
`yewtube v2.9.0` ignores url query parameters.
