### ISSUE TITLE
attempting to play song returns "Problem playing last item: (song) ERROR: NCMxxCKr5pc: Youtube says: This video is unavailable."

### ISSUE THREAD

**Issue by SirFireball3521** [mps-youtube/yewtube#1068]
## Issue / Suggestion
I installed this earlier today and after inserting my own API key, was able to search Youtube. however, when I attempted to play any of the results, I recieved the error in the title:
```
Problem playing last item: (song) ERROR: NCMxxCKr5pc: Youtube says: This video is unavailable.
```
I can confirm that the song exists and is available for me where I am.
## Your Environment
```
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2019.01.17
Python version     : 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/sirfireball/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
```

**Comment by HutchTy** [comment]
I'm having the same issue across every Youtube player I've tried -- mps-youtube, youtube-viewer, and straw-viewer.

**Comment by maxwell-herrmann** [comment]
I'm having the same issue, I just recently installed mps-youtube. This happens for every video every time.

**Comment by jlamoure** [comment]
I too have this issue using my own Youtube API key.
Running mps-youtube 0.2.8

**Comment by poyenc** [comment]
To solve the **unavailable** issues, just update the **youtube_dl** python module to the latest version

```bash
$ youtube-dl --version
2020.06.16.1
```

**Comment by maxwell-herrmann** [comment]
I have verified that youtube-dl is up to date (2020.06.16.1) but still see the issue.

**Comment by poyenc** [comment]
@maxwell-herrmann you can try using `pip3` to upgrade **youtube-dl** according to the [download page](http://ytdl-org.github.io/youtube-dl/download.html), since your Python version is **3.6.9**
```bash
$ pip3 install --upgrade --user youtube_dl
```

**Comment by maxwell-herrmann** [comment]
Thank you that solved it and updated the version of youtube-dl that mpsyt was using. I had to delete the old cache in .config (I referred to issue #1076) and now everything works perfectly. Thanks @poyenc!
