### ISSUE TITLE
--force-media-title requires the "=" (with the latest mpv build?)

### ISSUE THREAD

**Issue by oskarvid** [mps-youtube/yewtube#1069]
I just compiled mpv from source and I couldn't run mpsyt without adding a "=" to the --force-media-title flag in the mps_youtube/g.py file on line 78.

## Issue / Suggestion
  
I expect mpsyt to play music.
  
Add the "=" sign to --force-media-title flag on line 78 in the mps_youtube/g.py file to fix the bug.

## Your Environment

  
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.03.08
Python version     : 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/oskar/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
  
**Ubuntu 18.04.4, kernel 5.3.0-42-generic.**
  
mpv 0.32.0-302-g7768452f2d Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Mar 23 11:40:21 CET 2020
FFmpeg library versions:
   libavutil       56.42.101
   libavcodec      58.76.100
   libavformat     58.42.100
   libswscale      5.6.101
   libavfilter     7.77.100
   libswresample   3.6.100
FFmpeg version: N-97033-gc455a28a9e

**Comment by deracinator** [comment]
this is already fixed in the develop branch, use `pip` or `git clone` to use the latest mpsyt version, the master branch of this repository.  It seems that some leading members of mpsyt org development are not active, including the main maintainer unfortunately, it's a shame that an update is **utterly** required because things are breaking up and a new release is not out yet.
