### ISSUE TITLE
Youtube Error 403: Access Not Configured.

### ISSUE THREAD

**Issue by ghost** [mps-youtube/yewtube#1084]
## Issue
When searching for something, the following message appear 
```Youtube Error 403: Access Not Configured. YouTube Data API has not been used in project 422897895433 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=422897895433 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.```

## Your Environment
Archlinux on 5.6.10-arch1-1
mpsyt install via pacman
mpsyt version      : 0.2.8
notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.05.03
Python version     : 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0]
Processor          : AMD Ryzen 7 3750H
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.6.10-arch1-1-x86_64-with-glibc2.2.5
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/edricus/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : fr_FR.UTF-8

**Comment by anteklincic** [comment]
Does this mean you can't browse youtube without free software anymore? If you use the API you created for yourself, then youtube can identify you, right?
Any ideas how to search yt with free software?

**Comment by TitouanLazard** [comment]
Hi,

I had the same issue, I recreated my own API key through the google interface and deleted the cache (rm ~/.config/mps-youtube/cache_py_*). And it solves the issues. 
It might be need for those already using their own key, to recreate a new project, but I'm not 100% sure yet.
I hope it helps :)

**Comment by edricus** [comment]
> Hi,
> 
> I had the same issue, I recreated my own API key through the google interface and deleted the cache (rm ~/.config/mps-youtube/cache_py_*). And it solves the issues.
> It might be need for those already using their own key, to recreate a new project, but I'm not 100% sure yet.
> I hope it helps :)

Thanks it works.  
Link to create his own API: https://console.developers.google.com  
Create your API in the "credentials" tab. Copy it and paste it in mpsyt with `set api_key <your_key>`

**Comment by fmartingr** [comment]
For the rest of the people coming here, this is documented on the wiki: https://github.com/mps-youtube/mps-youtube/wiki/Troubleshooting#youtube-error-403-the-request-cannot-be-completed-because-you-have-exceeded-your-quota

**Comment by TitouanLazard** [comment]
Hi, 
It doesn't look to be exactly the same issue, here it's not about an exceeded quota, it looks more like a configuration problem on the Youtube API key. It might not be needed to create/use your own key, maybe simply removing the cache file could be enough.

**Comment by misterybodon** [comment]
I am very unexperienced and supposed there was something wrong but this solves the problem. Just to put all comments in an answer:

1. go here and create an account https://developers.google.com/ 
2. go here https://console.developers.google.com/project and click on "Create Project"
3. Somewhere you'll see "Youtube Data Api V3" (this new version is why we need a key, it seems). Click on it and next press "Enable"
4. Click on "Credentials" and "Create Credentials", now you get the key!
5. Open mpsyt and then set api_key <key value>

You will probably have to quit the app and re open it, but it worked out for me so far.
