### ISSUE TITLE
Error parsing commandline option Title

### ISSUE THREAD

**Issue by smileservices** [mps-youtube/yewtube#1085]
Executed a search and wanted to play a song. It didn't play and it gave this error

## Issue / Suggestion
Exiting... (Fatal error)
Error parsing commandline option title: option requires parameter  

## Your Environment

mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2020.03.24
Python version     : 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.4.0-29-generic-x86_64-with-glibc2.29
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/vladimir/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

Ubuntu 20.04

**Comment by bogdantomasciuc** [comment]
I face this issue too.

**Comment by LittleWhite-tb** [comment]
Got the same problem on Linux Manjaro
```
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.05.08
Python version     : 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.19.121-1-MANJARO-x86_64-with-glibc2.2.5
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/alexandre/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : fr_FR.UTF-8
```

**Comment by LittleWhite-tb** [comment]
Found how to bypass this one. I changed my audio/video player. Usually, I am using `mpv`. By setting it to `vlc` the music does play correctly.
Thus, I am thinking that the problem is linked on how `mpv` is invoked.

**Comment by LittleWhite-tb** [comment]
More investigations:
The command to call mpv is the following:
```
mpv https://r3---sn-hgn7rn7y.googlevideo.com/videoplayback?expire=1589643570&ei=0rS_Xv2oDfmfxN8PuoGeqAw&ip=2a01%3Acb14%3A2c7%3A1e00%3A402a%3A9928%3A1d3e%3Afe9b&id=o-AEQjxQ6ET4zdxyYWw8utohEcGHRjFM9RlUGSNK5tE10R&itag=251&source=youtube&requiressl=yes&mh=pK&mm=31%2C26&mn=sn-hgn7rn7y%2Csn-4g5edned&ms=au%2Conr&mv=m&mvi=2&pl=30&gcr=fr&initcwndbps=795000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4312882&dur=245.461&lmt=1575732515135752&mt=1589621867&fvip=6&keepalive=yes&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPSsGonB5Y4uHIjPiqM55RM2m2fDgfbClFCZwrNSZPzBAiB6tbjJpH3XjYdPwqDT9ifl5P_1jk4WyV5hIvKpYY_SIg%3D%3D&sig=AOq0QJ8wRQIhALlfyblTT1QW7Ow7BDN2ygSRRzNBlGzpJxMjrxPsZ23HAiAnirrbBZKgDoAO_-Wk2dRccDUr0OBSpW_rUin0W35YoQ==&ratebypass=yes
```
(With some additional IPC options not relevant here)

When using thie command in terminal, mpv start youtube-dl to get the video. youtube-dl results in error 403.
This can be reproduced using:
```
youtube-dl https://r3---sn-hgn7rn7y.googlevideo.com/videoplayback?expire=1589643570
```

I guess the initial issue is because mpv dies before mpsyt has the time to send additional control command to mpv.

**Comment by deracinator** [comment]
Always make sure to **read** some already created issues before creating a new one, this is already fixed for months by #1053

**Comment by LittleWhite-tb** [comment]
I confirm the fix. I used the version from git and it is now working properly. Thank you !

**Comment by AyoungDukie** [comment]
See #1069 for reference. 
In defense of the OP
1. The linked issue appears to be the only I could find that notes this problem, and it pertains to building from source for MPV, so at first blush may not seem to pertain to mps-youtube while browsing issues.
2. As you yourself noted in the linked thread, currently no distributed version of mps-youtube has this, so the workarounds essentially are to
- Use an alternate player to MPV (or alternatively use an older MPV build)
- Use a development version of mps-youtube

**Comment by GokulNC** [comment]
If you're on Windows:

- `pip uninstall mps-youtube`
- `pip install git+https://github.com/mps-youtube/mps-youtube/`

Ensure the latest `mpv` is installed (atleast v0.32). Use: https://mpv.io/installation/
- As soon as you open your player by `mpsyt`, do `set player mpv`

Should work now. If you face any errors, just search the issues tab.

**Comment by mahendrap1512** [comment]
I solved it by 
- first downloaded mplayer using `sudo apt install mplayer`
- then `set player mplayer`
That's it and now i can enjoy music on terminal 
Mplayer is a terminal based player.

**Comment by GlennOu66304** [comment]
> Found how to bypass this one. I changed my audio/video player (`set player vlc`). Usually, I am using `mpv`. By setting it to `vlc` the music does play correctly.
> Thus, I am thinking that the problem is linked on how `mpv` is invoked.

Agree with this solution on my Ubuntu 20, just set the VLC as my default audio and video player, then issue gone, thank you for the answer.

**Comment by elquimista** [comment]
1. https://github.com/mps-youtube/mps-youtube/issues/1085#issuecomment-667908462
2. https://github.com/mps-youtube/mps-youtube/pull/1092
