### ISSUE TITLE
ValueError: time data does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

### ISSUE THREAD

**Issue by francutura** [mps-youtube/yewtube#1086]
## Issue / Suggestion
I have the following issue when trying to search for playlist by for example doing `//test`
`ValueError: time data '2015-10-23T19:17:36Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'`

Changing the way youtube date time is parsed fixed the problem for me.
file util.py in function yt_datetime line 315:
`time_obj = time.strptime(yt_date_time, "%Y-%m-%dT%H:%M:%SZ")`
and line 325.

Can submit a PR with a fix?

## Your Environment
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.05.08
Python version     : 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/fran/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

**Comment by philor1** [comment]
thank you! ....I had the same problem and your solution fixed it for me

**Comment by ximi75** [comment]
thank you your solution it works for me too

OS: Manjaro Linux x86_64 
 Kernel: 5.6.11-1-MANJARO

**Comment by tigerjack** [comment]
Your fix works for me also. Just out of curiosity: do you know why the stack trace shows a different line number? For me it's 346 f.e., while the actual bugged line was at 315.

**Comment by navya-xx** [comment]
Same here..
OS: Ubuntu 18.04
Kernel: Linux 4.20.10-042010-generic

**Comment by rochr4** [comment]
lol, every week something brakes, hilarious state this ap is now, what state it is now ?.. 
Thank You @francutura

**Comment by qquq** [comment]
Yep, the proposed fix worked for me too. Thx!

**Comment by hypnull** [comment]
We should add a condition to check for the "." included date format in case YouTube decides to rollback to that old format or it's used in any cached/older playlist data

**Comment by philippkeller** [comment]
Yay, the fix works for me too!

IMO the PR was not yet merged. To use it already:

```bash
git clone git@github.com:mps-youtube/mps-youtube.git
cd mps-youtube
git fetch origin pull/1088/head
git checkout -b pullrequest FETCH_HEAD
./mpsyt
```

**Comment by trames57** [comment]
The "Date" field was also not showing from the set columns variable.  This also fixed that issue.
In arch linux, it is in /usr/lib/python3.8/site-packages/mps_youtube/util.py

**Comment by antffs** [comment]
Many thanks - works fine now with Pi Zero
