### ISSUE TITLE
HTTP not supported in Windows 10

### ISSUE THREAD

**Issue by SimonGhoul** [mps-youtube/yewtube#1111]
I can't stream any video with mps-youtube (I type pl https://www.youtube.com/playlist?list=PLe5BK_FUTqyxnBokKE3dh-kS4ET9ibWgJ). It always gives me the error "HTTP is not supported". I am going to detail what I did to install this.

## Installation

I recently downloaded this(mpsyt-0.2.8.exe but I renamed it to mpsyt.exe), I placed it on a folder that has youtube-dl.exe, mpv.com, mpv.exe, ffmpeg.exe, ffplay.exe, ffprobe.exe, and gifski.exe (not on the subfolders). I believe this is how you are supposed to install this (ignoring the unnecessary exes mentioned, those are there for different reasons)

Additionally, I followed this https://github.com/mps-youtube/mps-youtube/issues/986#issuecomment-612665074 (dnhuan came up with the fix) which led me to install python both through the website and through the windows store (for some reason, when I did it through the website the commands below didn't work. when I typed "python" it took me to the windows store). I ran the commands as instructed in the comment
pip3 install --upgrade mps-youtube
pip3 install pafy -U
pip3 install --upgrade youtube-dl
They all said it worked and they were all updated. And I still have this issue. I also tried copying python.exe and pythonw.exe into the folder where I have mpsyt.exe and it didn't work.

I hope you guys can help me out. I had also set my api key which worked succesfully (didn't have the quota exceeded issue anymore). I couldn't find anyone facing the same issue as me aside from those who managed to fix it using the steps above. This is the first time I am using this.

## Your Environment
Windows 10 2004

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.06.11
Python version     : 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Processor          : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.19041
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\camil\AppData\Roaming\mps-youtube

**Comment by SimonGhoul** [comment]
I tried running the commands again today. For some reason my api key wasn't saved so I had to set it again (I did exit after setting it)
I had also ran the commands above again and everything got updated including python, but it still hasn't been solved. I am gonna leave some screenshots here.
![image](https://user-images.githubusercontent.com/41213690/90393057-085bc100-e05e-11ea-90b6-5b7ff7c09b2e.png)
![image](https://user-images.githubusercontent.com/41213690/90393111-1f021800-e05e-11ea-80af-259c8386f747.png)
![image](https://user-images.githubusercontent.com/41213690/90393222-49ec6c00-e05e-11ea-8417-2755dba27c7c.png)
![image](https://user-images.githubusercontent.com/41213690/90393380-9df75080-e05e-11ea-9622-633121a8cb50.png)

**Comment by UpstateLloyd** [comment]
Same issue

**Comment by iamtalhaasghar** [comment]
I was having same issue today with python 3.9.0.
Switched to python 3.7.0 and then on python 3.8.0 and mpsyt was working with both of these python versions.

**Comment by phamwon** [comment]
> I was having same issue today with python 3.9.0.
> Switched to python 3.7.0 and then tried it on python 3.8.0. To my surprise, mpsyt was working fine with both of these python versions.

Using another version does not work, it's the same error.
