### ISSUE TITLE
Need a new windows binary built

### ISSUE THREAD

**Issue by Raketemensch** [mps-youtube/yewtube#1115]
The windows binary available on the Releases page is from 2018, and is missing lots of crucial new stuff. For example, it currently doesn't work at all because it uses http.

## Issue / Suggestion
YouTube said: HTTP is not supported.

We need a newer build, it looks like this was fixed in the end of 2019.

## Your Environment
Windows10
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.06.11
Python version     : 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.190
0 64 bit (AMD64)]
Processor          : AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.18362
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\fnord\AppData\Roaming\mps-youtube
env:TERM           : xterm-256color
env:SHELL          : c:\windows\system32\cmd.exe

**Comment by tommysolsen** [comment]
I would be glad for anyone who can help me with this as I don't run Windows on any machines.
If anyone would be able to do this in the form of a github action, then that would be perfect as we could then autogenerate these binaries on releases

**Comment by iamtalhaasghar** [comment]
Related #1035

**Comment by iamtalhaasghar** [comment]
Related #850
