### ISSUE TITLE
Tracks finishing before end. Runtime Warning message in player.

### ISSUE THREAD

**Issue by eyrent** [mps-youtube/yewtube#1117]
When playing back (audio-only) I get a 'RuntimeWarning' right at the line before the last one (playback position, cursor, volume indicator, etc). Tracks end prematurely. 

>  /usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
self.stdout = io.open(c2pread, 'rb', bufsize)

It doesn't prevent playback. However I noticed tracks finish before reaching the end, pretty consistently at about 84% (most songs are 4-5 min) effectively and annoyingly cutting them short. Replaying and seeking to almost the end makes the player actually play the last bit with no problems. I'm not sure if those issues are correlated. 

My Environment

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.09.14
Python version     : 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.4.0-47-generic-x86_64-with-glibc2.29
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/fabricio/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US

OS -> Ubuntu 20.04.1 LTS
PLAYER -> mplayer
I'm using my own api key.

Thanks.

**Comment by eyrent** [comment]
I can confirm nominal behaviour and no warnings using mpv as player.

**Comment by ChickenMan4236** [comment]
I have the same problem
