### ISSUE TITLE
Can anyone tell me why videos are not playing in the highest resolution?

### ISSUE THREAD

**Issue by django0212** [mps-youtube/yewtube#1124]
Whenever I play a video it doesn't play in the highest possible resolution. Most of the videos are playing in 360p and sometimes some are playing in 720p, but never higher.

I'm using Linux Mint and I'm using VLC as the player.

**Comment by trames57** [comment]
mps-youtube uses ytdl to retrieve the videos. Have you run ytdl -s <url> to see what the highest resolution available is from the YouTube API?

**Comment by iamtalhaasghar** [comment]
`yewtube v.2.10.0` doesn't have this issue.
