### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LymonP2** [mps-youtube/yewtube#1129]
Make sure you're using e.g. '--title=value' instead of '--title value'.

Error :pensive:

**Comment by Nassiel** [comment]
Confirmed. Using MPS with Arch Linux pacman installation and I receive the same error. Cannot reproduce any video.

**Comment by Masacaai** [comment]
Uninstall the version you have and pip install the experimental development branch. I fixed the issue by doing that.

**Comment by scoronado12** [comment]
I fixed it by installing the `mps-youtube` from the AUR. The standard Arch Package seems to not be up to par with what mpv requires.
