### ISSUE TITLE
Audacious stops too early

### ISSUE THREAD

**Issue by itsfarseen** [mps-youtube/yewtube#1130]
If I use audacious as the player with mpsyt, it stops playback in the middle.

Config:
![image](https://user-images.githubusercontent.com/40014472/101527164-aa0f7100-39b3-11eb-9dff-b8bf6f39dc55.png)

**Comment by SeanPaulCampbell** [comment]
I have a similar problem with mplayer.

**Comment by iamtalhaasghar** [comment]
Duplicate of #242
