### ISSUE TITLE
HTTP not available from YouTube. 

### ISSUE THREAD

**Issue by HackedByATree** [mps-youtube/yewtube#1132]
So first I fixed the api key, and now I am having a problem where I get this error after I search: ERROR: irhR5SkqswE: YouTube said: HTTP is not supported.

I have tried to upgrade everything and I have no idea what to do now.

**Comment by GhostVaibhav** [comment]
Same here

**Comment by iamtalhaasghar** [comment]
[Duplicate] Same as #1111
