### ISSUE TITLE
Search user error

### ISSUE THREAD

**Issue by cyvas8x** [mps-youtube/yewtube#1151]
![2021-03-07-230745_1280x768_scrot](https://user-images.githubusercontent.com/44058169/110246492-64564a80-7f9a-11eb-9c9b-a2a94349d4ca.png)
## Issue / Suggestion
i got this error, How to fix it? 
## Your Environment
mpsyt version : 0.2.8
Ubuntu 16, Python3.7

**Comment by iamtalhaasghar** [comment]
works fine with latest version `v2.9.0`
