### ISSUE TITLE
Not compiling mplayer on M1 arm64 aarch Macs

### ISSUE THREAD

**Issue by logiota** [mps-youtube/yewtube#1168]
A way around mplayer for arm since mps-youtube seems to compile fine.

This is what I get from a non Rosetta terminal on a MacBook Air M1:
user@MacBook-Air ~ % brew install --build-from-source mps-youtube

==> Downloading https://ghcr.io/v2/homebrew/core/yasm/manifests/1.3.0_2-1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/yasm/blobs/sha256:398b7f3d8a22e43b5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imlib2/manifests/1.7.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imlib2/blobs/sha256:9455235701eb3e7
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libcaca/manifests/0.99b19_3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libcaca/blobs/sha256:49547bb139e2ed
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256
######################################################################## 100.0%
Error: mplayer: no bottle available!
You can try to install from source with:
  brew install --build-from-source mplayer
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
user@MacBook-Air ~ % brew install --build-from-source mplayer
==> Downloading https://ghcr.io/v2/homebrew/core/yasm/manifests/1.3.0_2-1
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/9b737a173ca28f62fe02ec418f8e1048b429aee489e88930f54705c225e6a746--yasm-1.3.0_2-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/yasm/blobs/sha256:398b7f3d8a22e43b5
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/f3a34896f13b883221abf8bfbf182eeb494926d06c7ad2ea37996b13972ae491--yasm--1.3.0_2.arm64_big_sur.bottle.1.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/imlib2/manifests/1.7.1
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/bcadd4ba67b85034043ba18c07a5a568a468ad24dbaab7f48b979a5528406d07--imlib2-1.7.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/imlib2/blobs/sha256:9455235701eb3e7
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/bb9c0505f0b5c9eb3a32d5df8407af929c9fc07330c5f327cd124e1f20d5215b--imlib2--1.7.1.arm64_big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libcaca/manifests/0.99b19_3
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/1e794cbe87aed12c98bcfdb507776cbae77cdfa8ee745ca238b0360d6ed4902c--libcaca-0.99b19_3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libcaca/blobs/sha256:49547bb139e2ed
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/755163d8ba5adda339d10682616aff86804a3898572682b863880bce6d5f8e60--libcaca--0.99b19_3.arm64_big_sur.bottle.tar.gz
==> Downloading https://mplayerhq.hu/MPlayer/releases/MPlayer-1.4.tar.xz
######################################################################## 100.0%
==> Installing dependencies for mplayer: yasm, imlib2 and libcaca
==> Installing mplayer dependency: yasm
==> Pouring yasm--1.3.0_2.arm64_big_sur.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/yasm/1.3.0_2: 46 files, 3.3MB
==> Installing mplayer dependency: imlib2
==> Pouring imlib2--1.7.1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/imlib2/1.7.1: 62 files, 2.9MB
==> Installing mplayer dependency: libcaca
==> Pouring libcaca--0.99b19_3.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libcaca/0.99b19_3: 46 files, 3.4MB
==> Installing mplayer
==> ./configure --cc=clang --host-cc=clang --disable-cdparanoia --prefix=/opt/homebr
==> make
Last 15 lines from /Users/user/Library/Logs/Homebrew/mplayer/02.make:
        ldrh x8, [x0]
             ^
In file included from libavfilter/drawutils.c:27:
In file included from ./libavutil/intreadwrite.h:68:
./libavutil/arm/intreadwrite.h:46:14: error: invalid operand for instruction
    __asm__ ("strh %1, %0" : "=m"(*(uint16_t *)p) : "r"(v));
             ^
<inline asm>:1:7: note: instantiated into assembly here
        strh x8, [x0]
             ^
8 errors generated.
make: *** [ffmpeg/libswresample/libswresample.a] Error 2
make[1]: *** [libavfilter/drawutils.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [ffmpeg/libavfilter/libavfilter.a] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

user@MacBook-Air ~ % mps-youtube 
zsh: command not found: mps-youtube

**Comment by Calamigos** [comment]
Same here

**Comment by Juliusfrank11** [comment]
same

**Comment by gerkov77** [comment]
same thing here in 2022.02

**Comment by mrezabayat** [comment]
+1

**Comment by alexdwagner** [comment]
Did anyone find a fix here?

**Comment by iamtalhaasghar** [comment]
As this issue is related to `mplayer` thus kindly report a bug [here](http://www.mplayerhq.hu/DOCS/HTML/en/bugreports_report.html).
