### ISSUE TITLE
Cannot set player as mpv on Fedora

### ISSUE THREAD

**Issue by genmonsrc** [mps-youtube/yewtube#1195]
I downloaded mpv on Fedora 35 using snap following this tutorial: https://snapcraft.io/install/mpv/fedora. Then I did "set player mpv" but it returned "Player application mpv not found". How do I install mpv on Fedora? mps-yt version: 0.2.8

**Comment by iamtalhaasghar** [comment]
Try,
`sudo dnf install mpv`
