### ISSUE TITLE
hardcoded client_secret

### ISSUE THREAD

**Issue by firmianay** [mps-youtube/yewtube#1199]
Hi, I see that client_secret is hardcoded into the program, not very sure if this can cause harm?

```py
def generate_credentials():
    """Generate the token. Please respect these credentials :)"""
    credentials = oauth2.SpotifyClientCredentials(
        client_id='6451e12933bb49ed8543d41e3296a88d',
        client_secret='40ef54678fe441bd9acd66f5d5c34e69')
    return credentials
```

**Comment by iamtalhaasghar** [comment]
@ritiek are you sure you want to keep these api keys in the project code? Pls respond.
Closing issue for now,

**Comment by ritiek** [comment]
@iamtalhaasghar I remember creating a new Spotify account only to generate these API keys, so it should be alright to continue using these. I don't remember the username password any more though, so you'll want to create a new account to get more control/see analytics.
