### ISSUE TITLE
 moosingin3space/mps-youtube Unable to find package: python3-mps-youtube

### ISSUE THREAD

**Issue by Konglomneshued** [mps-youtube/yewtube#1200]
Trying to install this on Fedora Linux, saw  moosingin3space/mps-youtube created a package for it on Fedora.

## Issue / Suggestion

Followed his instructions and the package isn't found:
`sudo dnf copr enable moosingin3space/mps-youtube`
then
![Screenshot from 2022-12-13 17-03-13](https://user-images.githubusercontent.com/94726665/207464379-86dc6082-21d2-4b06-b149-9393b7cff073.png)

## Your Environment

Fedora Linux 37.

**Comment by iamtalhaasghar** [comment]
For now stick to the recommended installation method using `pipx`.
