### ISSUE TITLE
Not playing videos

### ISSUE THREAD

**Issue by FreeBornAngel** [mps-youtube/yewtube#1227]
I'm trying to play videos for 2 days now and they don't play.
I reload them, and nothing.
They play on youtube, but who wants that?

## Your Environment

I see 14 scripts are being blocked by brave shields, this has not been an issue up to now.
Videos played just fine with shields up in the recent past.

Privacy Redirect redirects videos to other instances that won't play either, but I had always been able to change to yewtu.be and the videos would play.
Kavin.rocks hasn't worked for a long time, it buffers every 1 to 1.5 seconds making watching unbearable.

I'm using linux mint and brave.

**Comment by FreeBornAngel** [comment]
Now it seems to be working when initially launched from the search link, but when reloaded will not reload.
It is also cutting off randomly creating the same issue.

**Comment by iamtalhaasghar** [comment]
`yewtube` (formerly mps-youtube) is a cli tool to play youtube videos on terminal. You are confusing it with `yewtube` invidious instance. You should create issue on invidious project repos not here

**Comment by FreeBornAngel** [comment]
Oh, thanks.
