### ISSUE TITLE
Playback Controls Inputting as text inputs instead of Controlling Volume, Seeking, etc.

### ISSUE THREAD

**Issue by AyoungDukie** [mps-youtube/yewtube#1230]
After having to reinstall on PipX due to some glitches, Yewtube stopped accepting the MPV control key bindings on the interface. CTRL+C works still, however others do not appear to work.

After stopping playback, previous hotkey entries appear as input text at the next prompt (i.e. pressing 9 multiple times for volume reduction appears as "99999..."

## Issue / Suggestion

Occurs after the following steps:
 - Search for a result and select an entry, 
 - Then attempt to control playback via keyboard controls. 

A interesting note on the input issue; pressing a string of inputs together and then pressing ENTER will  not visually do anything during playback, but the attempted command entry will register a subsequent entry. If the number is a valid choice (i.e. "9"), then closing playback with CTRL+C will return to the prompt and then immediately launch the selected entry. If it is not valid, "Invalid Item / range entered!" will appear above the prompt.

Using "show_video" will allow direct entry MPV to work, but it still will not work on the yewtube window. It does prevent the Text entry issue from above, however.
## Your Environment

Version info
```
yewtube version    : 2.10.2
yt_dlp version     : 2023.03.04
Python version     : 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Processor          : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.19044-SP0
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\<USER>\AppData\Roaming\mps-youtube
dbus               : None
glib               : False
env:TERM           : xterm-256color
```

Config:
```
  Key                 Value
  order             : relevance
  user_order        :
  max_res           : 2160p
  player            : mpv.exe
  playerargs        :
  encoder           : 0 [None]
  notifier          :
  checkupdate       : True
  show_player_keys  : True
  fullscreen        : False
  always_repeat     : False
  columns           :
  ddir              : C:\Users\<USER>\Downloads\mps
  overwrite         : True
  show_video        : False
  search_music      : False
  window_pos        :
  window_size       :
  download_command  :
  lookup_metadata   : True
  lastfm_username   :
  lastfm_password   :
  lastfm_api_key    :
  lastfm_api_secret :
  audio_format      : auto
  video_format      : auto
  pages             : 3
  autoplay          : False
  set_title         : True
  mpris             : False
  show_qrcode       : False
  history           : True
  input_history     : True
  vlc_dummy_interface : False
  show_subtitles    : True
```

**Comment by JodanJodan** [comment]
Could you try `set player mpv.com`?

**Comment by AyoungDukie** [comment]
This does seem to work around the issue, as does using alternative players like `mpvnet.exe`.

Any ideas why the .exe would fail to receive the keyboard inputs? I recall using them before and hadn't changed this setting since the original install

**Comment by iamtalhaasghar** [comment]
> This does seem to work around the issue, as does using alternative players like `mpvnet.exe`.
> 
Thus closing this issue!
