### ISSUE TITLE
Issue concerning the setup of (custom) music player

### ISSUE THREAD

**Issue by ElizabethWega** [mps-youtube/yewtube#1240]
**Yewtube version:** 2.10.4
**OS:** Windows 10
**Music player used:** none
**Issue description:** Every time I boot up yewtube using the command line, I am met with the following message: _←[93mFailed to get mplayer.exe`s version. Probabily it is not installed. Try installing it again or change player using `set player <player_name>` ←[0m
Press Enter to go back to main menu._
Since I'm more familiar with mpv, I installed the third-party GUI by shinchiro on SourceForge. After seeing that installing mpv on my computer resulted in another disappointment (I used the _set player mpv_ command and this was the output: _Player application mpv.exe not found_), I tried copying and pasting the mpv.exe file into yewtube's directory on my computer. I typed in the command yet again and it still will not work. Any tips on how to solve this are greatly appreciated! Thank you in advance!

**Comment by iamtalhaasghar** [comment]
Make sure the path, where mpv.exe or mplayer.exe is installed, is present in PATH environment variable.

**Comment by ElizabethWega** [comment]
> Make sure the path, where mpv.exe or mplayer.exe is installed, is present in PATH environment variable.

Oh my, it works! Thank you so much!

**Comment by binrusdi** [comment]
I have entered the PATH environment variable but nothing happens and the error is still the same

**Comment by iamtalhaasghar** [comment]
> I have entered the PATH environment variable but nothing happens and the error is still the same

paste the value of your PATH environment variable here.

**Comment by binrusdi** [comment]
alright, it's work
thank you very much
