### ISSUE TITLE
Can't change yt.dlp yewtube uses even after installing the newer one in all the ways I coud

### ISSUE THREAD

**Issue by whatever4kindle** [mps-youtube/yewtube#1245]
Can't play anything.

yewtube version    : 2.10.4
yt_dlp version     : 2022.07.18
Python version     : 3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.4.0-146-generic-x86_64-with-Ubuntu-18.04-bionic
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/victor64/.config/mps-youtube
dbus               : None
glib               : False
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US

and the result of the command yt-dlp --version is

 yt-dlp --version: 2023.07.06

**Comment by iamtalhaasghar** [comment]
Check #1249
