### ISSUE TITLE
Playback stops after a few seconds

### ISSUE THREAD

**Issue by ju-sh** [mps-youtube/yewtube#1246]
## Issue / Suggestion
No matter which video is chosen, the playback gets stuck at 4s or 5s and doesn't go beyond that for some reason.
Tried updating yewtube via pip, but still no change.

It was working fine a few weeks ago. Could it be because some change youtube made or something?

## Your Environment
I'm using mpv without video to play the media on Ubuntu.

```
yewtube version    : 2.10.4
yt_dlp version     : 2023.07.06
Python version     : 3.7.9 (default, Aug 18 2020, 06:22:45)
[GCC 7.5.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/ju-sh/.config/mps-youtube
dbus               : None
glib               : False
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_IN
env:LANGUAGE       : en_IN:en
```

**Comment by galgot** [comment]
Have same problem, but the playback last longer, though never goes up to the end of the track.

**Comment by iamtalhaasghar** [comment]
Closing this issue. If this happens again feel free to create a new issue.
