### ISSUE TITLE
A way to queue/shuffle the entire playlist rather than just the visible entries

### ISSUE THREAD

**Issue by tildezero** [mps-youtube/yewtube#1259]
As of right now, if you run `shuffle` after searching for a playlist using `pl`, it will only shuffle the songs that are currently visible. Similarly, if you play an entire playlist with using `1-`, it will only play the items that are currently on the screen. When I listen to playlists, I generally want to listen to the entire thing, without having to change pages after every 20 songs, so I think it would be really nice if there were a setting (something like `queue_full_playlist`) that rather than shuffling/queueing just the page, it queues/shuffles the entire playlist or however many pages are searched. 

## Environment
- yt version 2.9.0

**Comment by Reycho** [comment]
You can shuffle and queue the entire playlist, just run "shuffle all" and then "play all".
Hope this helps.
