### ISSUE TITLE
yt command doesn't work

### ISSUE THREAD

**Issue by krishna-r-parmar** [mps-youtube/yewtube#1264]
yt command is not working. 

## Issue
I have installed yewtube using
`pip3 install yewtube`

After successful installation, the `yt` command doesn't work and gives back following error:
`zsh: command not found: yt`

## Your Environment
python 3.12
pip 23.2.1
MacOS Ventura 13.5.2

**Comment by keeranbz** [comment]
Use the following to find the location of the 'yt' script so you can add that folder, where pip installs scripts, to your PATH.

```bash
find / -name yt
```
