### ISSUE TITLE
how to JUST PLAY AUDIO please guide without missing any step :-))

### ISSUE THREAD

**Issue by HakaishinShwet** [mps-youtube/yewtube#1269]
how to easily play JUST AUDIO, no video downloading and playing needed in my case then what and how can i do please explain in detail if this thing is possible if now please add this as feature who just wanna listen music with this great program :-))

**Comment by shawokou123** [comment]
1、set
2、set show_video Flase

so you can play music instead of video.

**Comment by mlliarm** [comment]
> 1、set 2、set show_video Flase
> 
> so you can play music instead of video.

A minor correction for the second step:

2. `set show_video False`

**Comment by iamtalhaasghar** [comment]
as it has already been answered hence closing issue
