### ISSUE TITLE
'yt' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by bob4444-test** [mps-youtube/yewtube#1281]
Unable to start yewtube
## Issue / Suggestion
I just installed yewtube with pip install yewtube and now when I type to run by tying yt into the console, I get the error "'yt' is not recognized as an internal or external command,
operable program or batch file."
yt

## Your Environment

win10

**Comment by Grim73** [comment]
had this with my macOS instance running on pipx, had to run `pipx ensurepath`, looks like this may be something similar
