### ISSUE TITLE
A option to scrobble lastfm music from normal search

### ISSUE THREAD

**Issue by Pekrio** [mps-youtube/yewtube#1287]
## Issue / Suggestion

Everytime i want to hear my favorite artist´s music, it always go to some random video with the music with the subtitles. If possible, would be very helpful to scrobble with //album-name :)

## Your Environment

LMDE 6 Faye
6.1.0-25 Kernel

**Comment by iamtalhaasghar** [comment]
I have no intention & time to support lastfm & features related to it. I will keep yewtube alive to support browsing of youtube videos through CLI as long as I can do without any api.
PR's are welcomed thou if someone wants to support lastfm features in yewtube :)
