### ISSUE TITLE
Command not found after installing

### ISSUE THREAD

**Issue by seyekuyinu** [mps-youtube/yewtube#138]
After installing using Homebrew, I typed in mpsyt. I got 
-bash: mpsyt: command not found. 
I tried reinstalling MPlayer but it said it was already installed.
What do I do?

**Comment by liutauras** [comment]
I have installed older version of mpsyt from Ubuntu repo. And then installed new one with pip. Version remained old. I removed old mpsyt from Ubuntu packages. Repeated first steps on: https://github.com/np1/mps-youtube#installation

 -bash: mpsyt: command not found.

pip install shows:
Successfully installed mps-youtube-0.2.7.1 pafy-0.5.3.1
Ubuntu 16.04
