### ISSUE TITLE
Can't download the video which include non-english title

### ISSUE THREAD

**Issue by carlcarl** [mps-youtube/yewtube#150]
Hi,

Here is my command: `dlurl https://www.youtube.com/watch?v=WpCqMRlp3eE`
The result: `Problem playing last item: 'ascii' codec can't encode character u'\u7b2c' in position 50: ordinal not in range(128)`

Please help resolve this issue.

**Comment by Vrihub** [comment]
FYI, I just ran into the same problem; I can't download  videos with non-ASCII characters in the title, though I can play them.

I tried the PYTHONIOENCODING workaround described above and it works, so I added it to the wiki page https://github.com/mps-youtube/mps-youtube/wiki/Troubleshooting

mpsyt version      : 0.2.7.1
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.04.26
Python version     : 3.5.2+ (default, Dec 13 2016, 14:16:35) 
Platform: Linux
sys.stdout.enc     : UTF-8
default enc        : utf-8
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : xxx.UTF-8
