### ISSUE TITLE
mps-youtube v 0.2.1 keeps 'retrying' after closing the video

### ISSUE THREAD

**Issue by GijsTimmers** [mps-youtube/yewtube#156]
Using mps-youtube v 0.2.1 on WIndows 7.

`show_video` is set to True. I'm using mplayer.exe to play video.

When playing a song, I might want to stop the current track, and play another one. When I do that, mps-youtube says `error: retrying` and will restart the current track.

This happens when pressing <kbd>Q</kbd> to close the video, and when closing it by using the window close button. Pressing <kbd>Ctrl</kbd> + <kbd>C</kbd> when the error appears works.

**Comment by AshlynnInWonderland** [comment]
I'm also having this problem on Arch Linux using mpv.

**Comment by ids1024** [comment]
@AshlynnInWonderland Your problem is likely caused by issue #155.  A fix has been committed, but not released. Try mps-youtube-git.

**Comment by ids1024** [comment]
@sa3m Are you using the git version? The stable version of mpsyt does not work with mpv 0.7 on Unix.  This is fixed in the develop branch.

**Comment by AshlynnInWonderland** [comment]
That fixes it. Thanks!

Do you know any timeline for when it'll be released? I like to stay away from git packages when possible.
