### ISSUE TITLE
Audio MP3

### ISSUE THREAD

**Issue by ghost** [mps-youtube/yewtube#162]
How do you download the MP3 audio?

**Comment by postadelmaga** [comment]
I am using mps on my android phone ( using termux ) and everything works fine ! except the mp3 conversion:
- I have installed ffmep and set encoder to 1 but it still download in webm 
Anything I can do to debug the issue ?

**Comment by ardyfeb** [comment]
> I am using mps on my android phone ( using termux ) and everything works fine ! except the mp3 conversion:
> 
> * I have installed ffmep and set encoder to 1 but it still download in webm
> 
> Anything I can do to debug the issue ?

Same issue
