### ISSUE TITLE
Show playing progress

### ISSUE THREAD

**Issue by erkiha** [mps-youtube/yewtube#38]
Please implement showing play progress (within a song) in command window, this would be useful in combination with seek functionality to see at a glance how far we are to help find specific place. In relation to this it would be sometimes useful to start playing in specific place in song/video by entering mm:ss for starting place.

**Comment by VeNoMouS** [comment]
This appears to be broken again...
```
[cplayer] mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Mar 17 06:56:30 UTC 2015
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.20.100
[cplayer]    libavcodec      56.26.100
[cplayer]    libavformat     56.25.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.11.102
[cplayer]    libswresample   1.1.100
```
