### ISSUE TITLE
Date column not displaying properly

### ISSUE THREAD

**Issue by cverver** [mps-youtube/yewtube#537]
When i add the date column to the search results, it doesn't handle 9-digit dates well, showing the year as 201.

1/1/2016 is fine
31/12/2016 is fine and shows as 31/12/16
7/10/2016 is not fine and shows as 7/10/201

![2016-10-07 22_13_36-mpsyt](https://cloud.githubusercontent.com/assets/16956043/19204214/caf0927a-8cdb-11e6-899c-4c90da82e12e.png)

Manually specifying the date column to be 10 wide works, but results in horrible alignment of the years.

![2016-10-07 22_18_43-mpsyt](https://cloud.githubusercontent.com/assets/16956043/19204264/1ad97f9a-8cdc-11e6-8f25-04df23fe5b61.png)

I would suggest giving 1-digit day and month numbers a leading zero (and remove the first two digits of the year OR _always_ have the first two digits of the year display, not both).
So that this happens:
1/1/2016 => 01/01/16
31/12/2016 => 31/12/16
7/10/2016 => 07/10/16
Unfortunately i don't know python, and have a lot of other things to do, otherwise i would have created a pull request myself.

**Comment by ids1024** [comment]
I'm not seeing this behavior. What is the full output of `mpsyt --version`? What specific query resulted in this?

**Comment by cverver** [comment]
My PC is off for today, so i can't show you the full output.
I can tell you that i downloaded the .exe (the one with python in it) from the latest release this evening.
So following the most easy windows install with the latest version should reproduce the exact state.

**Comment by cverver** [comment]
```
C:\just\any\folder>mpsyt --version
[mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.1 (youtube-dl backend)
youtube-dl version : 2016.07.07
Python version     : 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
Processor          : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
Machine type       : AMD64
Architecture       : 32bit, WindowsPE
Platform           : Windows-8-6.2.9200
sys.stdout.enc     : cp437
default enc        : utf-8
Config dir         : C:\Users\Username\AppData\Roaming\mps-youtube](url)
```
I have cygwin installed, my locale is EN_US, but i have dutch format for stuff like numbers and dates.

**Comment by mave-rick** [comment]
I am not getting to reproduce this. Does it still exist? If so, what was the terminal size and your config?
