### ISSUE TITLE
VLC Playback not supported on Linux Mint 18.1 

### ISSUE THREAD

**Issue by Flubbex** [mps-youtube/yewtube#590]
How to reproduce:
1. Install Mint 18.1
2. Install mps youtube and youtube dl through pip3
3. set player vlc
4. Endless loop of retries
xplayer works fine but doesn't support streams. 
No error output other than "Error: retrying".

**Comment by ids1024** [comment]
The properly supported players are mpv and mplayer, with mpv being the preferred choice. That said, vlc has worked in the past, so I don't know why it would be an issue.
