### ISSUE TITLE
this not work :D in the your main function.

### ISSUE THREAD

**Issue by catafest** [mps-youtube/yewtube#611]
[mythcat@localhost ~]$ python
Python 2.7.13 (default, Jan 12 2017, 17:59:37) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from . import config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Attempted relative import in non-package

`Can you help me !?`

**Comment by ids1024** [comment]
> Python 2.7.13

Mpsyt requires Python 3.
