### ISSUE TITLE
how can i pause music with python file

### ISSUE THREAD

**Issue by fevzican** [mps-youtube/yewtube#622]
Hi, i am using Rpi 3. I can stop or pause music on the terminal with keyboard, but i want to access to these commands with a python file. I tried many things, but i couldnt success it. I mean, when i played the music, i want to pause or stop this music, but i cant access to media player controls with python file. I prefer to Mpv or Vlc player. Do you have any suggest?

**Comment by Razesdark** [comment]
One way of achieving this would be to run mpsyt in tmux or screen. Both of those programs allow you to send keystrokes to the software from the terminal. That way you can make a command that sends the appropriate keystrokes to pause the software, which you can invoke by passing them as arguments to os.system() in python.

https://serverfault.com/questions/178457/can-i-send-some-text-to-the-stdin-of-an-active-process-running-in-a-screen-sessi

Here is a stackexchange post detailing the commands you need to to make it work.

**Comment by ritiek** [comment]
Here is a little tool [muxnect](https://github.com/ritiek/muxnect) I wrote on top of tmux. I can confirm it works with mpsyt.

**Comment by ids1024** [comment]
Mpsyt can be controlled though the mpris2 API.

**Comment by iamtalhaasghar** [comment]
You might also want to look at `playerctl`
