### ISSUE TITLE
using latest pip3 install 

### ISSUE THREAD

**Issue by Ofloo** [mps-youtube/yewtube#624]
http://asciinema.org/a/1q9b1q01ydy0sapwvu0h8f7t3

**Comment by justijndepover** [comment]
Having the same problem here. can you show us the output of `mpsyt --version`

**Comment by justijndepover** [comment]
This has been addressed here: https://github.com/rg3/youtube-dl/issues/12885

Looks like you a problem with youtube itself. You can wait on the developers to fix the problem or you could change the following line in `/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py`:

```
r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/watch_as3|/html5player(?:-new)?|/base)?\.(?P<ext>[a-z]+)$',
```
to
```
r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/[a-z]{2}_[A-Z]{2})?(?:/watch_as3|/html5player(?:-new)?|/base)?\.(?P<ext>[a-z]+)$',
```

**Comment by jifilis** [comment]
@justijndepover 
It Works!!! Tks

Not forget the full line with the  `player_url)`

`r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/[a-z]{2}_[A-Z]{2})?(?:/watch_as3|/html5player(?:-new)?|/base)?\.(?P<ext>[a-z]+)$', player_url)`
