### ISSUE TITLE
ERROR: Signature Extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by ElArcangel** [mps-youtube/yewtube#653]
Hi, I'm receiving the error on the subject when using MPSYT.exe for windows. apparently is youtube-dl that is outdated but since I assume is embbeded on the excel itself, I'm not sure if there's a way I can get the new youtube-dl and force MPSYT to use that one or if you should update the youtube within the mpsyt on your end.

Any help appreciated.
![youtube-dl](https://user-images.githubusercontent.com/29766524/27669334-8855b8c2-5c5c-11e7-8e3d-63940864ff52.JPG)

**Comment by CrowsOfWar** [comment]
Same issue here. The python version is causing issues as well.
