### ISSUE TITLE
"Problem playing last item" error

### ISSUE THREAD

**Issue by urielz** [mps-youtube/yewtube#698]
Anyone knows how to fix this error?  It shows up randomly when trying to open a video:

_Problem playing last item: [Errno 2] No such file or directory: '<notifier'_

-thanks

**Comment by ritiek** [comment]
> It shows up randomly when trying to open a video

Does this happen every time you try to play a video or just random chance?

**Comment by urielz** [comment]
It's random in the sense that it happens only with some videos- but for those videos it happens every time. I'll switch to the dev branch and see if it makes a difference. Thanks.

**Comment by ids1024** [comment]
Weird. Do you have a notifier set? (Run the `set` command to see settings.)
