### ISSUE TITLE
Player skips to the next item in the middle of playback

### ISSUE THREAD

**Issue by MrMino** [mps-youtube/yewtube#709]
Player is moving to the next song (if on playlist, otherwise just exits playback) before ending the current one.

Happens on Ubuntu 16.04.3 LTS with `mplayer` (installed with `apt`).

Steps to reproduce:
1. `> / Rival Sons radio`
2. `> 1`
3. Wait for it
4. There. It skips to the next song at random.

I tried to debug it with `ipdb`, but doing it on this code base (and threads) is apparently out of my league.

Switching to `mpv` fixed the problem (I think).

**Comment by MrMino** [comment]
Also happens on Fedora 25 - seems to be OS independent.

**Comment by Razesdark** [comment]
Could this be a bandwith issue? mpsyt starts downloading the song and mplayer reaches the end of the buffer before the entire file is downloaded, mplayer thinks it is at the end of the file and exits?

**Comment by MrMino** [comment]
I no longer use the software in question, and it's unlikely that this issue is reproducible / still exists. Closing.
