### ISSUE TITLE
Play music without stoppage on Rpi

### ISSUE THREAD

**Issue by shivasiddharth** [mps-youtube/yewtube#714]
Hello,
if VLC is used for music playback, the music would stop halfway through, instead use chromium.

use this command to set chromium as default player:
`mpsyt set player chromium-browser, set playerargs ,exit`

you can stop the music by:
pkill chromium

Hope you guys find it usefull.

**Comment by ritiek** [comment]
That's cool, I didn't know browsers could be used as players too. By the way, I suggest you to use mpv-player, it is lighter and has got more features.
