### ISSUE TITLE
Python Issues?

### ISSUE THREAD

**Issue by vartira** [mps-youtube/yewtube#766]
## Issue / Suggestion
I used "mpsyt" and searched for "/lofi" and got results. I tried to play a video (not a stream) and I got this error:
                                                                                                                                                                   [1/12>
Traceback (most recent call last):                                                                                                                                                
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/commands/play.py", line 85, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 41, in play_range
    returncode = _playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 148, in _playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object is not subscriptable

## Your Environment

mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2017.05.18.1
Python version     : 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.9.0-4-amd64-x86_64-with-debian-9.3
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/vartira/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

Could my issue be that I'm using an older version of something?

**Comment by kraetzin** [comment]
It looks like your version of `youtube-dl` is out of date. Try updating that and see if it helps.

**Comment by arooni** [comment]
question: same typa setup, except I have the latest youtube and latest youtube-dl on mac.  

when i open mps-youtube then do
url https://www.youtube.com/watch?v=1Cs0qyG78qY 

output is ==> requested format is not available.  ideas?

I believe that your software supports streaming right?

**Comment by kraetzin** [comment]
Indeed, and that stream works for me. What is the output of `mpsyt --version`? Usually these sorts of issues come from an out of date `youtube-dl`, especially on distros such as Debian where the package in the repos is older. Installing `youtube-dl` via `pip3` fixes this.

**Comment by arooni** [comment]
[I]  ~  mpsyt --version
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.02.14
Python version     : 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-17.4.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/david/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /usr/local/bin/fish
env:LANG           : en_US.UTF-8
[I]  ~  youtube-dl --version
2018.01.27
[I]  ~ 

**Comment by arooni** [comment]
So my youtube-dl is pretty up to date and I have the latest released mpsyt (at least according to homebrew).  ideas?

**Comment by Razesdark** [comment]
There hasnt been an official release of a new version number in over a year. I would assume your version is from then. I suggest trying the current development branch as mpsyt has had plenty of development since then.

**Comment by arooni** [comment]
So from my research it looks like you install from a branch this way:

 pip3 install -U  git+https://github.com/mps-youtube/mps-youtube.git@develop

I did that but no improvement.  Am I installing it wrong?

**Comment by arooni** [comment]
Also why does it see the wrong version of youtube-dl?  It's seeing one  from Feb 2017

**Comment by arooni** [comment]
Nevermind; I got it.  pip3's version of youtube-dl was much less recent than homebrews version.  uninstalling youtube-dl on pip3 and then reinstalling it makes things work

**Comment by arooni** [comment]
unrelated question; with set show_video false ;; while it sets it correctly ; i still see videos. looking for audio only

**Comment by Rom1deTroyes** [comment]
On Debian 9 stable, worked by : 
`apt remove youtube-dl` 
`pip3 install youtube-dl`
`youtube-dl -U`
`youtube-dl --version` tells : youtube-dl version 2018.03.03
and everything goes round (-:
