### ISSUE TITLE
q doesn't stop for repeat songs

### ISSUE THREAD

**Issue by SanketDG** [mps-youtube/yewtube#806]
Play any song on repeat, and press `q`, it will just restart the song.

## Your Environment

mpsyt `develop` branch

Fedora 27

mpv

**Comment by iamtalhaasghar** [comment]
I've merged changes from your commit https://github.com/vn-ki/mps-youtube/commit/dbb04a9c73310885315a8d476d911b6c29342563
Thanks @vn-ki
