### ISSUE TITLE
Application crashes if the video is blocked by the copyright holders

### ISSUE THREAD

**Issue by ac130kz** [mps-youtube/yewtube#837]
The title is pretty much self explanatory, but as I saw in the code, there is a "pass" for videos that cannot be played, so I cannot suggest a solution for it. I'm also not sure whether it's an issue with mps-youtube or dl-youtube/pafy, because the error message that I get is just a mess.

PS I also could not get next/previous keys (< and >) working both on Windows and Ubuntu, are they currently broken?

## Issue / Suggestion
Not to waste any space here, I'll put the error message on [gist](https://gist.github.com/ac130kz/5d05ff626180edacbf9f3494deba2b62)

## Environment
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.03.14
Python version     : 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.15.0-22-generic-x86_64-with-Ubuntu-18.04-bionic
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/ac130kz/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US
OS: xubuntu 18.04
mpv 0.27.2

**Comment by ac130kz** [comment]
I think that with a bit of debugging one of this functions should be modified to catch this specific issue
```
stream_details 
_playsong
```

**Comment by postfalk** [comment]
Please catch this KeyError. Otherwise mpsyt is awesome.

**Comment by sdmunozsierra** [comment]
Latest 0.2.8 git version has this fix. 
You can install it by typing:
`$ pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git`

**Comment by postfalk** [comment]
Awesome

**Comment by tchernomax** [comment]
@sdmunozsierra "except KeyError" isn't present in https://github.com/mps-youtube/mps-youtube/blob/master/mps_youtube/player.py#L48 version 0.2.8 (event on master).
(There is a "except TypeError", which isn't the same… and doesn't fix this bug).

I personally changed "except TypeError:" to "except:" and it fix the problem.
