### ISSUE TITLE
Maintainers for mps-youtube and pafy, and possibly moving off of GitHub

### ISSUE THREAD

**Issue by ids1024** [mps-youtube/yewtube#841]
I took over maintaining mps-youtube from @np1 in 2015 (#259). But I haven't really been using mps-youtube (or the dependent pafy library) lately, let alone writing code for it.

I think it might be best to add some of the major contributors as collaborators, and set it so that changes have to go through pull requests and be reviewed. That way, at least one other collaborator will have to approve any changes (it looks like GitHub also allows requiring 2, 3, etc. reviews). This depends on what those contributors think of this idea.

Looking at the list of contributions, the top contributors other than me and @np1 are, in order (by number of commits), @JKatzwinkel, @kraetzin, @hrnr, @ritiek, @Razesdark, @vn-ki.

Also, we can discuss here if mps-youtube should move to another platform like GitLab. For those who aren't aware, this has suddenly become rather popular since Microsoft's acquisition of GitHub. When that happened @np1 deleted the mps-youtube and pafy repositories from GitHub, but they're restored now. I personally think a more open platform like GitLab would be better, all else being equal, but other concerns might outweigh that. I haven't really used GitLab, so I don't know how it compares. What do other contributors think?

**Comment by ac130kz** [comment]
Before I had a "student" account on GitHub, I was looking for free private repos. Almost one year all of my private stuff was on Bitbucket, but it was really slow, painful to use. Moving to GitLab took literally 2-3 minutes (they provide export feature). That was about 4-5 months ago and now I understand that GitLab is surely a great option.

**Comment by ids1024** [comment]
Looking more carefully at GitLab, it seems like a more mature and functional platform than I thought; it may have some disadvantages of GitHub, but it also has some solid advantages over GitHub like integrated CI. I suppose it's been improving.

I don't know if it's worth moving, but it's a solid option.

@JKatzwinkel, @kraetzin, @hrnr, @ritiek, @Razesdark, @vn-ki Any thoughts?

**Comment by Razesdark** [comment]
I've been using Gitlab for private repos for a while and I am positive to the platform in general. I've been using their CI stuff and it both work and is presented well. In general I like the platform as much if not even more than Github. It has intermittently felt somewhat sluggish however.

I haven't used Microsoft products nor followed them close enough to really have any strong opinions either way except I wasn't tempted to go back to win10 with the whole privacy and telemetry thing in both the OS and .net core. I don't think MS will be a good influence on GitHub, but I don't have any strong opinions on the matter.

That being said, I would not be opposed to a move, if only because I like Gitlab a lot.

**Comment by ritiek** [comment]
I tried out GitLab recently and it seemed nice to me as well. If we're going to shift there, maybe it would still be a good idea to keep a mirror here to GitLab?

**Comment by ids1024** [comment]
GitLab has built in support for [mirroring](https://docs.gitlab.com/ce/workflow/repository_mirroring.html), so that's easy enough. I suppose we would want to disable the issue tracker on GitHub (there's no way to disable PRs); I don't know what the best way to refer people to the new location would be.

If no one has particularly strong opinions, we can stay on GitHub for now, keeping this in mind if the situation changes (GitHub gets worse, or GitLab gets even better). GitHub does make the barrier to contributing lower, but that may be changing as people become more acquainted with GitLab.

**Comment by vn-ki** [comment]
I don't particularly like or hate GitLab. In fact, I'm a bit more comfortable with GitHub mostly because I know my way around. 

I also don't have any strong hate towards MS projects. In fact I think what they are doing with VSCode is amazing.

I am agreeing with @ids1024 here. Stick with GitHub for now, because it a lot more popular than any other similar org. If the situation changes (GitHub becomes unpopular/unusable) we can always switch.

**Comment by ritiek** [comment]
Thanks @ids1024!

> I don't know what the best way to refer people to the new location would be.

Just the basic stuff should suffice I guess like put a heading on top of README telling users that further development is taking place on GitLab (and maybe mentioning something like GitLab is friendly place for development too lol, to invite future contributors). Just this to take care maybe if we're going to move in future.

That said, I don't have any strong opinion on (Microsoft) GitHub or GitLab either.

> Really, today's Microsoft sucks a bit less than yesterday's (though they still have a long way to go); and who knows what they'll open source tomorrow. So lets see how things go.

That's how I think too.

**Comment by hrnr** [comment]
Hi all,

I intend to maintain MPRIS-related parts of mps-youtube, more of less what I have been doing so far. I don't have much free time for anything else.

Regarding Github/Gitlab I would strongly prefer to stay on Github, unless they introduce changes worsening our experience. All the other projects I contribute to are on Github and I think they are going to stay, at least for this time.

**Comment by markkrj** [comment]
@ids1024 Can't np1 remove the project from https://pypi.org/project/mps-youtube/?? You and him are listed as maintainers there...

**Comment by ids1024** [comment]
@markkrj For reference, he restored the repositories himself when I emailed him, and added me back as an owner. Since he doesn't use mps-youtube anymore and isn't involved with development, he said those still involved could decide whether or not to stay on GitHub, and said I could remove his access from the repositories. So I don't think there's really any danger there (I don't think Microsoft can acquire the Python Software Foundation; they're a non-profit :laughing:), but I've removed him there anyway since he's no longer involved.

Relatedly, I suppose I could add someone else to pypi as well, but I'll have to document the release process first. It's somewhat complicated (and could perhaps be improved).

@hrnr Sounds good. As you say, that's more or less what I expected since you were basically maintaining that already (and doing a good job at it).

**Comment by kraetzin** [comment]
Just chiming in on the Github/Gitlab issue. I haven't really seen a strong argument for moving to GitLab yet. As far as I can tell it doesn't offer any tangible benefits over Github. I'm no fan of Microsoft, but I would personally take the wait and see approach to what they do with Github before making a decision. If/when they start changing Github into something that makes life more difficult for us, then we can move to GitLab or \<insert alternative\>. The door is always open.

I'm happy to join as a collaborator and look forward to working with everyone on mpsyt. :grinning:
