### ISSUE TITLE
Appveyor CI

### ISSUE THREAD

**Issue by ids1024** [mps-youtube/yewtube#850]
It would be good to set up Appveyor for Windows .exe builds. Done correctly, this should allow us to have a .exe for the latest nightly, and make releasing easier (I've been booting my rarely-used Windows VM just to build an exe to attach to mps-youtube releases).

**Comment by hrnr** [comment]
Could we support windows users from pip as anyone else? That would save us some effort.

We could improve the readme to link some guide to get pip running on windows and give pip install instructions to windows users.

**Comment by Razesdark** [comment]
I think its kind of neat that we do support Windows out of the box, even though I never used it. 

The main issue in my opinion is dependency management, in particular youtube-dl. If we could for example just bundle mpsyt with self contained python and pip binaries we could potentially initiate updates from inside of mpsyt and have everything happend in the background

**Comment by ids1024** [comment]
> The main issue in my opinion is dependency management, in particular youtube-dl.

Yes, that is an issue. Youtube-dl needs to be updated quite frequently, which has been breaking the py2exe builds. Automated CI builds could help with that.

The other issue here seems to be that none of us actually use Windows.
