### ISSUE TITLE
Can't play anything after upgrading to 0.2.8

### ISSUE THREAD

**Issue by nukeop** [mps-youtube/yewtube#885]
System: Linux Mint
I just upgraded both mps-youtube and youtube-dl from pip to newest versions. Now I can't play anything anymore. I can search, but after selecting a song, it finds a stream, and abruptly stops, then returns to search results with no error messages.

**Comment by nemanjan00** [comment]
Same here.

**Comment by ritiek** [comment]
Make sure your youtube-dl version is atleast `2018.09.10` otherwise upgrade it:
```
$ youtube-dl --version
2018.09.10
```

Also, are you directly able to invoke youtube-dl and fetch the URL for audio stream?
```
$ youtube-dl https://www.youtube.com/watch?v=yysk8s2vih8 -xg
https://r7---sn-ci5gup-qxa6.googlevideo.com/videoplayback?keepalive=yes&itag=251&ei=XR...
```

**Comment by nukeop** [comment]
Like I said, I updated youtube-dl along with mpsyt, it's on 2018.09.10. And it's able to download videos by itself.

**Comment by Ace17** [comment]
Same for me: 
```
pi@mediabox:~ $ youtube-dl --version
2018.09.08
```

**Comment by Ace17** [comment]
Same for me:
```
pi@mediabox:~ $ youtube-dl --version
2018.09.10
```

**Comment by nemanjan00** [comment]
Apperently reinstalling youtube-dl using pip resolved this for me.

**Comment by Flubbex** [comment]
Same, reinstalling youtube-dl with pip does not fix anything. There is a very painful, glaring issue in the current release where the `omxplayer` command is being ran without the appropriate tags to surround the parameters. If you run said command by hand and manually add the tags these videos will play normally.  Is this project still being actively worked?

**Comment by Ace17** [comment]
> There is a very painful, glaring issue in the current release where the `omxplayer` command is being ran without the appropriate tags to surround the parameters. If you run said command by hand and manually add the tags these videos will play normally.

Very interesting.

This might explain why the rare songs that mps-youtube can currently play seem to have "simple" titles.

Do you have the number for the issue you're referring to?

**Comment by nukeop** [comment]
Updating python 3 and reinstalling helped me solve this.

**Comment by paulbrodersen** [comment]
Same problem here despite setting up a clean venv with a fresh install of youtube-dl and mps-youtube. Interestingly, I can still download files (just not play them directly from within mps-youtube).

**Comment by rafaeln** [comment]
> OK I think I got one clue.
> 
> The failure occurs before the actual invocation of mpv, and thus isn't related to the player. If I comment out the call in player.py / _launch_player, I'm able to play all songs again!
> 
> ```
> --- .local/lib/python3.6/site-packages/mps_youtube/player.py	2018-09-13 07:59:45.899179458 +0200
> +++ /tmp/player.py	2018-09-22 20:23:27.336126330 +0200
> @@ -389,14 +391,14 @@
>      # not supported by encoding
>      cmd = [util.xenc(i) for i in cmd]
>  
> -    metadata = util._get_metadata(song.title)
> +    # metadata = util._get_metadata(song.title)
>  
> -    if metadata == None :
> -        arturl = "https://i.ytimg.com/vi/%s/default.jpg" % song.ytid
> -        metadata = (song.ytid, song.title, song.length, arturl, [''], '')
> -    else :
> -        arturl = metadata['album_art_url']
> -        metadata = (song.ytid, metadata['track_title'], song.length, arturl, [metadata['artist']], metadata['album'])
> +    # if metadata == None :
> +    arturl = "https://i.ytimg.com/vi/%s/default.jpg" % song.ytid
> +    metadata = (song.ytid, song.title, song.length, arturl, [''], '')
> +    # else :
> +    #     arturl = metadata['album_art_url']
> +    #     metadata = (song.ytid, metadata['track_title'], song.length, arturl, [metadata['artist']], metadata['album'])
>  
>      input_file = None
>      if ("mplayer" in config.PLAYER.get) or ("mpv" in config.PLAYER.get):
> ```

These changes made it work again for me. Reinstalling mps-youtube and youtube-dl did not.

**Comment by arteteco** [comment]
@rafaeln thanks, I edited player.py as you suggest and it works now for me too. File is in `/usr/local/lib/python3.4/dist-packages/mps_youtube` in debian 9 too.

I tried reinstalling youtube-dl, mps-youtube, updating python3, nothing worked except that modification.

**Comment by Warlkiry** [comment]
@rafaeln Worked for me after commenting every single line with reference to var metadata (in your fix you didn't commented g.mprisctl.send(('metadata', metadata)) things. Thanks now I got my Daft Punk on o/
