### ISSUE TITLE
error code 1

### ISSUE THREAD

**Issue by githubgnulinux** [mps-youtube/yewtube#939]
install mps-youtube --upgrade
Collecting mps-youtube
  Using cached https://files.pythonhosted.org/packages/b1/8e/5156416119545e3f5ba16ec0fdbb2c7d0b57fad9e19ee8554856cd4a41ad/mps-youtube-0.2.8.tar.gz
    Complete output from command python setup.py egg_info:
    Mps-youtube requires python 3.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AHDO0W/mps-youtube/

**Comment by ids1024** [comment]
> Mps-youtube requires python 3.

I think that message is pretty self explanatory. Install with python3.
