### ISSUE TITLE
mpsyt-0.2.8.exe signature extraction failed

### ISSUE THREAD

**Issue by polettix** [mps-youtube/yewtube#944]
`mpsyt-0.2.8.exe` shows the same issue as #938 - although in this case the suggestion to upgrade `youtube-dl` (https://github.com/mps-youtube/mps-youtube/issues/938#issuecomment-457851864) cannot be applied because it's a self-contained executable.

## Issue / Suggestion

This is shown when trying to play [this video](https://www.youtube.com/watch?v=yCXrgASzf50&t=3060s):

~~~~
> ERROR: Signature extraction failed: Traceback (most recent call last):
  File "site-packages\youtube_dl\extractor\youtube.py", line 1199, in _decrypt_signature
  File "site-packages\youtube_dl\extractor\youtube.py", line 1110, in _extract_signature_function
  File "site-packages\youtube_dl\extractor\youtube.py", line 1171, in _parse_sig_js
  File "site-packages\youtube_dl\extractor\common.py", line 880, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature [...]
~~~~

Upgrading `youtube-dl` and then re-releasing should address the issue.

## Your Environment

Windows 10, using `mpsyt-0.2.8.exe` self-contained executable.

**Comment by soanvig** [comment]
Bump.

I've got the same problem. My `youtube-dl` is 2019.04.17, and `mps-youtube` youtube-dl is 2018.09.10 and YT simply doesn't work on most videos.

What about allowing to use custom `youtube-dl`?
