### ISSUE TITLE
Problem when trying to play music: [SSL:CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by lightspot21** [mps-youtube/yewtube#945]
## Issue / Suggestion
Exactly the same bug described in #830, but on Ubuntu, not Mac OS. Also the issue did not offer a working solution for the problem (tried installing Certifi with `sudo pip3 install certifi` but it didn't work)
 
## Your Environment
OS: Lubuntu 18.04
mps-youtube version: 0.2.8
I don't use an external player (I have this only for music)

**Comment by pirate486743186** [comment]
i have Mate on ubuntu 18.04
and mps-youtube 0.2.8

It works fine for me.
It's still broken for you?

**Comment by lightspot21** [comment]
Yes, it still is.

**Comment by pirate486743186** [comment]
Both our systems are essentially the same underneath,so it should have just worked.

the external player is terminal only with out video. In set, you can see the player you are using.

you probably have mpv already installed. Install it if not. Try `mpv youtube-url`

Are you sure you have properly upgraded the system? `sudo apt update` should say in the end "All packages are up to date."

Try this:
`sudo apt-get install --reinstall ca-certificates python3-certifi python-certifi`

you have installed youtube-dl from pip3?
install
`sudo -H pip3 install youtube-dl`
upgrade
`sudo -H pip3 install --upgrade youtube-dl`
Can you download something from youtube with it?

there's no conflict with mps-youtube of the repos? check with`which mpsyt`

try deleting the config folder "/home/USER/.config/mps-youtube"

copy paste here the output of "mpsyt --version"
here's mine
```
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.03.09
Python version     : 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/*******/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US
```

**Comment by JPRuehmann** [comment]
I have the same Problem on Kubuntu 18.04 LTS (32Bit) is there a solution?
Delete the config Folder does not help.

**Comment by iamtalhaasghar** [comment]
duplicate of https://github.com/mps-youtube/yewtube/issues/973
