### ISSUE TITLE
ERROR: Unable to download webpage: Remote end closed connection without response 

### ISSUE THREAD

**Issue by gurumark** [mps-youtube/yewtube#988]
## Issue / Suggestion

Try to download audio of a video using
da 16
I get:
Search results for mary j                                                                                                                                                                                [1/10>
> da 16
ERROR: Unable to download webpage: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Your Environment

I am using android termux 

$ mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.05.20
Python version     : 3.7.3 (default, May  3 2019, 14:50:05) 
[Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
Processor          : 
Machine type       : aarch64
Architecture       : 64bit, 
Platform           : Linux-4.9.97-aarch64-with-libc
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /data/data/com.termux/files/home/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /data/data/com.termux/files/usr/bin/bash
env:LANG           : en_US.UTF-8

$ uname -a
Linux localhost 4.9.97 #1 SMP PREEMPT Thu Apr 11 17:38:07 CST 2019 aarch64 Android

$ mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun May  5 23:21:20 UTC 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.22.100
[cplayer]    libavcodec      58.35.100
[cplayer]    libavformat     58.20.100
[cplayer]    libswscale      5.3.100
[cplayer]    libavfilter     7.40.101
[cplayer]    libswresample   3.3.100
[cplayer] ffmpeg version: 4.1.3
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/data/data/com.termux/files/usr --disable-gl --disable-jpeg --disable-lcms2 --enable-libarchive --disable-libass --enable-lua --enable-pulse --enable-openal --disable-caca --disable-alsa --disable-x11
[cplayer] List of enabled features: 52arch android asm atomics build-date cplayer cplugins debug-build drmprime dummy-osd fchmod ffmpeg glibc-thread-name glob glob-posix gnuc gpl iconv libaf libarchive libav-any libavcodec libdl libm linux-fstatfs lua openal opensles optimize posix posix-or-mingw posix-spawn posix-spawn-android pthreads pulse stdatomic vt.h zlib
[cplayer] Reading config file /data/data/com.termux/files/usr/etc/mpv/encoding-profiles.conf
[cplayer] Reading config file /data/data/com.termux/files/usr/etc/mpv/mpv.conf
[cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun May  5 23:21:20 UTC 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.22.100
[cplayer]    libavcodec      58.35.100
[cplayer]    libavformat     58.20.100
[cplayer]    libswscale      5.3.100
[cplayer]    libavfilter     7.40.101
[cplayer]    libswresample   3.3.100
[cplayer] ffmpeg version: 4.1.3
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
[ytdl_hook] script-opts/ytdl_hook.conf not found. 
[ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[ytdl_hook] Exiting...
[stats] script-opts/stats.conf not found. 
[stats] lua-settings/stats.conf not found. 
[stats] Exiting...
[osc] script-opts/osc.conf not found. 
[osc] lua-settings/osc.conf not found. 
[osc] Exiting...

**Comment by ritiek** [comment]
Do you have the latest youtube-dl installed? Can I see your version:
```
$ youtube-dl --version
```

**Comment by gurumark** [comment]
Here you go:
$ youtube-dl --version
2019.05.20

**Comment by ritiek** [comment]
youtube-dl seems up to date. Are you able to manually download audio with youtube-dl?

See the YouTube video URL with:
```
i 16
```
in mpsyt where 16 is the number of the track failing to download.

Copy this YouTube video URL and see if you can manually call youtube-dl to download audio:
```
$ youtube-dl -x https://www.youtube.com/watch?v=....
```

**Comment by gurumark** [comment]
@ritiek Thanks for helping.
i 16
Problem playing last item: ERROR: Unable to download webpage: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.[1/10>

**Comment by gurumark** [comment]
The following works perfectly:
$ youtube-dl -ic --extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail --add-metadata https://www.youtube.com/watch?v=gYtybgToH2Q
[youtube] gYtybgToH2Q: Downloading webpage
[youtube] gYtybgToH2Q: Downloading video info webpage
[youtube] gYtybgToH2Q: Downloading thumbnail ...
[youtube] gYtybgToH2Q: Writing thumbnail to: Say - Black Earth ∙ Fazıl Say-gYtybgToH2Q.jpg
[download] Destination: Say - Black Earth ∙ Fazıl Say-gYtybgToH2Q.webm
[download] 100% of 8.39MiB in 00:28
[ffmpeg] Destination: Say - Black Earth ∙ Fazıl Say-gYtybgToH2Q.mp3

**Comment by ianforcements** [comment]
Having the same issue - when I run mpsyt -v I see that the youtube-dl version is reported as 2019.04.01, however when I run youtube-dl --version the reported version is 2019.05.20

**Comment by ritiek** [comment]
@ianforcements I see. Thanks for this! Probably @gurumark also has this problem of different (older) youtube-dl being used by mps-youtube as from the error message. You guys could try removing any previously installed versions of youtube-dl and mps-youtube with:

(Some of these commands will probably error out but that's okay)
```bash
sudo apt purge -y youtube-dl
sudo apt purge -y mps-youtube
python3 -m pip uninstall -y youtube-dl
python3 -m pip uninstall -y mps-youtube
pip3 uninstall -y youtube-dl
pip3 uninstall -y mps-youtube
```
And then try to install them fresh with:
```bash
pip3 install youtube-dl -U
pip3 install git+https://github.com/mps-youtube/mps-youtube.git
```
Things should hopefully work fine now.

**Comment by gurumark** [comment]
pip3 uninstall -y youtube-dl
pip3 uninstall -y mps-youtube
pip3 install youtube-dl -U
pip3 install git+https://github.com/mps-youtube/mps-youtube.git

$ mpsyt -v
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.05.20
Python version     : 3.7.3 (default, May  3 2019, 14:50:05) 
[Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
Processor          : 
Machine type       : aarch64
Architecture       : 64bit, 
Platform           : Linux-4.9.97-aarch64-with-libc
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /data/data/com.termux/files/home/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /data/data/com.termux/files/usr/bin/bash
env:LANG           : en_US.UTF-8
**********************
mpsyt uses the latest youtube-dl.
I still get the same error. I can use youtube-dl no problem there.
There is clearly something wrong with latest version.

**Comment by ritiek** [comment]
@gurumark Umm.. this is really weird. I have no idea what else might possibly be causing this.
